Fixed Minor Greece Tweaks
deliciousmods/1956_beta pull request #1784
Opened 2021-06-03 21:35 UTC by marijn2112

Excluded one additional bracket, should now match the config as in my testing

2021-06-04 00:08 UTC, Thinking-waffle requested changes
Don't accept this until after the monthly update, requires testing and marijn proper inclusion into the team.

2021-06-14 12:09 UTC, marijn2112 commented
Should only need 1 additional change namely changing the DLC tree to also use my altered 2nd ljbuljana award

2021-06-23 19:01 UTC, ilkober reviewed
Unsure about the changes to events/Germany.txt and "new" Greek event
The rest looks fine and has Fantoms seal of approval

2021-06-28 18:35 UTC, Thinking-waffle approved these changes

2021-06-28 18:36 UTC, merged