Waffle january 1
deliciousmods/1956_beta pull request #2466
Opened 2023-01-03 10:56 UTC by ilkober

I will make it a draft to make sure that this work doesn't get thrown out

2023-01-03 22:39 UTC, Thinking-waffle commented
The ukrainian content there is unfinished woops.

2023-01-05 20:23 UTC, marijn2112 requested changes, later dismissed
Bahrain/Qatar throw errors from using the pre-character system

2023-01-05 20:37 UTC, TheBrit7 commented
They very much do, they load into the game and everything.

2023-01-07 22:54 UTC, SpicyAlfredo approved these changes

2023-01-07 22:54 UTC, merged