Pepper peru 5
deliciousmods/1956_beta pull request #2768
Opened 2023-11-01 20:12 UTC by pepper419

-introduction of bop for peru between army and navy

-reform of the economic tree of Peru

-rebalancing of the equator tree from the war of '41

-rebalancing of some ideas from Peru

2023-11-24 23:41 UTC, marijn2112 reviewed
I still think you should remove division attack/defense from the BoP, maybe add some recovery rate instead (maybe (-)15 or 20% at most)
With naval too, would remove naval speed, hit chance and naval damage modifiers, not sure what it should be replaced with there, but your shells arent doing less damage because of morale or prestige

2023-11-29 12:57 UTC, marijn2112 requested changes
See above

2024-01-26 22:27 UTC, ilkober reviewed
You added 30 rubber to Acre state???
0 -> 30

2024-01-26 22:27 UTC, ilkober commented on history/states/1052-Acre.txt
Places 30 rubber instead of 0

2024-01-26 22:27 UTC, ilkober commented on localisation/english/replace/r56_formables_l_english.yml
Unifying Hispanoamerica as any other country buy Peru will make you Peru? Why?

2024-02-01 23:40 UTC, marijn2112 commented
Pepper as long as this is marked draft I wont check this, just a reminder

2024-02-04 00:27 UTC, marijn2112 commented
Error log

2024-02-04 00:28 UTC, marijn2112 commented
Previous feedback also still applies, theres still combat stats in the BoP

2024-02-14 01:21 UTC, closed without merging