added alternate ruler for communist germany
deliciousmods/1956_beta pull request #2889
Opened 2024-03-22 20:16 UTC by ItsFlor

If germany doesnt ally the USSR when going communist, Heinrich Brandler takes over the party and becomes the new country leader. germany gets a new colour and name

2024-03-22 23:04 UTC, marijn2112 commented
Personally dont like the idea of replacing a leader you just fought a civil war for

Also events should stick to the a/b/c standard

2024-03-30 20:01 UTC, ilkober requested changes, later dismissed
An event should provide options and not just forcefully change your leader.

Also, what is the colour change for?

2024-03-30 20:01 UTC, ilkober commented on common/characters/GER.txt
Character name should be stored in Characters file

2024-03-31 12:45 UTC, ItsFlor commented on common/characters/GER.txt
Other option is the mutually exclusive focus for leader
colour change is like trotzkyist ussr, they get a different colour too

2024-03-31 12:49 UTC, ilkober commented on common/characters/GER.txt
Event should make you be able to select a leader, not just forcing the change. Especially in context of potential USSR civil war and alignment of that kind

2024-03-31 15:42 UTC, ItsFlor commented on common/characters/GER.txt
added an additional option now

2024-04-10 08:09 UTC, ItsFlor commented
-updated tooltips for several focuses, making them more readable
-fixed issue with treaty of versailles path not being able to do the last focus
-added new name for communist germany, changes with alliance with the ussr or with brandler
-updated some focus icons to look more communist

2024-04-22 23:26 UTC, marijn2112 requested changes, later dismissed
Error log

2024-05-01 13:25 UTC, SwedishNorwegian approved these changes
LGTM

2024-05-01 13:25 UTC, merged