Monaco content and a few portraits
deliciousmods/1956_beta pull request #2910
Opened 2024-04-29 15:25 UTC by facundosim

- A few portraits for Uruguay and Brazil
- Monaco Content, which includes:
- Invasion of Monaco events
- Death of Louis II of Monaco
- Princes becoming national sprits upon change of governement
- Option to become a republic
- French option to intervene

Very crucial stuff

2024-04-29 22:29 UTC, ilkober requested changes

2024-04-29 22:29 UTC, ilkober commented on events/Monaco.txt
First even shoul happen on_actions, in particular on_state_control_change and include the trigger, making it is_triggered_only = yes.

Event should probably also check if Monaco is in faction and/or is puppet, otherwise option a steals a puppet/ally.



leave_faction = yes in the end implies that on historical a puppeted Monaco will leave the Axis, a puppet of their overlor, which is definitely weird.

For a second event "free Monaco", it checks for the flag which is assigned on immediate = {, meaning it will always be assigned, no matter if Monaco resists or accepts the inevitable

2024-04-29 22:29 UTC, ilkober commented on common/ideas/monaco.txt
Should use "ideas" and "modifier"  instead of "traits"

2024-04-29 22:29 UTC, ilkober commented on common/characters/MNC.txt
extra NOT or OR
			available = {
				NOT = {
					OR = {
						has_government = communism
					}	
				}
			}

2024-04-29 22:29 UTC, ilkober commented on common/country_leader/r56_traits.txt
Should be calle "_trait" instead of "_idea"

2024-04-29 22:29 UTC, ilkober commented on events/Monaco.txt
event.1 should probably ask Italy if they want to invade the defiant Monaco in first place

2024-04-29 22:29 UTC, ilkober commented on events/Monaco.txt
Same above applied to German occupation too.

Sidenote: news_events about occupation of Monaco should probably fire for, say, everyone in Western Europe/democratic nation/fighting Germany or similar. I doubt that South America, Central Africa or Japan would be knowing much of it.

2024-04-29 22:29 UTC, ilkober commented on events/Monaco.txt
monaco.9 should trigger on_government_change instead of mean_time_to_happen = [ days =1 }

2024-04-29 22:29 UTC, ilkober commented on events/Monaco.txt
Same applies to monaco.10 and monaco.11

2024-04-29 22:29 UTC, ilkober commented on gfx/interface/ideas/mnc/Louis_II.dds
Ideas naming should follow "r56_idea_[TAG]_[IDEA NAME]"

2024-04-29 22:29 UTC, ilkober commented on gfx/leaders/BRA/r56_Portrait_BRA_Field_Marshal_Prestes.dds
Naming of the character to full name instead of military rank
https://en.wikipedia.org/wiki/Lu%C3%ADs_Carlos_Prestes

2024-04-29 22:29 UTC, ilkober commented on gfx/leaders/BRA/r56_portrait_BRA_Dutra.dds
Same here

P.S. might need to adjust the correspoding portrait definitions in game files

2024-04-29 22:29 UTC, ilkober commented on gfx/leaders/BRA/r56_portrait_BRA_DutraPres.dds
Is there a difference to just BRA_Dutra?

2024-04-29 22:29 UTC, ilkober commented on gfx/leaders/BRA/r56_Portrait_BRA_Field_Marshal_Prestes.dds
Or use [NaME]_army instead

2024-04-29 22:29 UTC, ilkober commented on gfx/leaders/BRA/r56_portrait_BRA_Eurico_Gaspar_Dutra.dds
Same as other Dutras?

2024-04-30 02:42 UTC, facundosim commented on common/characters/MNC.txt
Fixed this

2024-04-30 02:43 UTC, facundosim commented on common/ideas/monaco.txt
I made it that way so that it displays the full title of the prince. Besides, some monarchs in vanilla use this

2024-04-30 02:47 UTC, facundosim commented on events/Monaco.txt
Oh, never used that function before. Monaco.11 shouldn't be triggered by that though, since Monaco could still decide to keep the prince

2024-04-30 04:33 UTC, facundosim commented on gfx/leaders/BRA/r56_portrait_BRA_Eurico_Gaspar_Dutra.dds
Honestly, no idea. I just replaced the ones already present

2024-04-30 04:35 UTC, facundosim commented on events/Monaco.txt
nvm I see what you mean. Changed it

2024-04-30 19:36 UTC, ilkober approved these changes
looks fine
@marijn2112 want to double-check?

2024-04-30 21:03 UTC, merged