Smol bugfix for Honduras and even smaller change for Turkey
deliciousmods/1956_beta pull request #2972
Opened 2024-07-11 09:26 UTC by dogukans1

As for Honduras:
1. "Support the USA" focus code is improved to make sure Honduras is joining USA against Fascist Germany, and accounted the case where USA takes over Allies. This focus' description explicitly states that Honduras wishes to join USA that fights German Reich
2. Added code to remove "Monroe Doctrine" spirit for every focus that used to remove US guarantee as US no longer simulates that by guarantees but rather a spirit

As for Turkey: "Modest Economic Liberalisation" focus is locked if Etaism focus is completed. This focus makes Celal Bayar the PM, which locks all paths associated to Etaism

2024-07-13 19:14 UTC, marijn2112 commented
Although the focus description may target Germany, we prefer the focus to be flexible

2024-07-14 06:23 UTC, dogukans1 commented
Reverted to the old state. Added bypass checks in case UK and/or US is no longer Democratic so a Democratic Honduras enjoyer doesn't get themselves locked on an ahistorcial game

2024-07-29 15:38 UTC, marijn2112 requested changes
Fixing some typos and seeing if the focus is flexible enough, then accepting

2024-07-29 16:02 UTC, marijn2112 approved these changes

2024-07-29 16:02 UTC, merged